title: szubrycht.pl
description: Kamil Szubrycht
baseurl: /
url: https://szubrycht.pl

header_pages:
  - index.md

style: dark

footer: '&copy; 2020 Kamil Szubrycht'

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

google_analytics: UA-168998787-1

url: "https://szubrycht.pl"
plugins:
  - jekyll-sitemap
