url: https://szubrycht.pl
title: szubrycht.pl
social:
  name: Kamil Szubrycht
  links:
    - https://twitter.com/kamilszubrycht
    - https://www.linkedin.com/in/kszubrycht
    - https://github.com/kszubrycht
baseurl: /

header_pages:
  - index.md

style: dark

footer: '&copy; 2020 Kamil Szubrycht'

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

google_analytics: UA-168998787-1

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
